import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ['Cabinet Grotesk', 'sans-serif'],
        body: ['Satoshi', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        '2xs': '0.625rem',
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: 'clamp(1rem, 2.5vw, 1.25rem)',
        '2xl': 'clamp(1.125rem, 3vw, 1.5rem)',
        '3xl': 'clamp(1.375rem, 3.5vw, 1.875rem)',
        '4xl': 'clamp(1.5rem, 4vw, 2.25rem)',
        '5xl': 'clamp(1.75rem, 5vw, 3rem)',
        '6xl': 'clamp(2rem, 6vw, 3.75rem)',
      },
      fontWeight: {
        regular: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
      },
      colors: {
        md: {
          surface: 'var(--md-surface)',
          onSurface: 'var(--md-on-surface)',
          'on-surface-variant': 'var(--md-on-surface-variant)',
          primary: 'var(--md-primary)',
          onPrimary: 'var(--md-on-primary)',
          'primary-container': 'var(--md-primary-container)',
          'on-primary-container': 'var(--md-on-primary-container)',
          outline: 'var(--md-outline)',
          'outline-variant': 'var(--md-outline-variant)',
          'surface-variant': 'var(--md-surface-variant)',
          'inverse-surface': 'var(--md-inverse-surface)',
        },
        token: {
          primary: 'var(--color-primary)',
          onPrimary: 'var(--color-onPrimary)',
          primaryContainer: 'var(--color-primaryContainer)',
          onPrimaryContainer: 'var(--color-onPrimaryContainer)',
          secondary: 'var(--color-secondary)',
          onSecondary: 'var(--color-onSecondary)',
          secondaryContainer: 'var(--color-secondaryContainer)',
          onSecondaryContainer: 'var(--color-onSecondaryContainer)',
          tertiary: 'var(--color-tertiary)',
          onTertiary: 'var(--color-onTertiary)',
          tertiaryContainer: 'var(--color-tertiaryContainer)',
          onTertiaryContainer: 'var(--color-onTertiaryContainer)',
          background: 'var(--color-background)',
          onBackground: 'var(--color-onBackground)',
          surface: 'var(--color-surface)',
          onSurface: 'var(--color-onSurface)',
          surfaceVariant: 'var(--color-surfaceVariant)',
          onSurfaceVariant: 'var(--color-onSurfaceVariant)',
          outline: 'var(--color-outline)',
          outlineVariant: 'var(--color-outlineVariant)',
          error: 'var(--color-error)',
          onError: 'var(--color-onError)',
          errorContainer: 'var(--color-errorContainer)',
          onErrorContainer: 'var(--color-onErrorContainer)',
          success: 'var(--color-success)',
          onSuccess: 'var(--color-onSuccess)',
          inverseSurface: 'var(--color-inverseSurface)',
          inverseOnSurface: 'var(--color-inverseOnSurface)',
          inversePrimary: 'var(--color-inversePrimary)',
        },
      },
      spacing: {
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
      },
      borderRadius: {
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 1px 3px rgba(13,16,33,0.08)',
        md: '0 4px 16px rgba(13,16,33,0.12)',
        lg: '0 8px 32px rgba(13,16,33,0.16)',
        xl: '0 16px 48px rgba(13,16,33,0.20)',
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
      transitionDuration: {
        fast: '150ms',
        base: '200ms',
        slow: '300ms',
      },
      keyframes: {
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        fadeUp: 'fadeUp var(--transition-base) ease forwards',
      },
    },
  },
  plugins: [],
}

export default config
